schema_version: "0.5.0"

gradient:
  samples: 20
  tolerance: 1.0
  smooth: 0.5
  dither: false

spcc:
  camera_mode: "OSC"
  sensor: "Sony IMX678"
  osc_filter: "DWARF Mini Astro"
  osc_lpf: ""
  white_reference: "Average Spiral Galaxy"
  catalog: "AUTO"
  bgtol_lower: -2.8
  bgtol_upper: 2.0


denoise:
  modulation: 1.0
  cosmetic_correction: true
  da3d: false
  independent_channels: false


deblur:
  psf_source: "STARS"
  symmetric_psf: false
  kernel_size: null
  iterations: 10
  regularization: "NONE"
  alpha: 3000
  multiplicative: false


ghs:
  method: "AUTO_GHS"
  auto:
    linked: true
    shadows_clip: -2.8
    stretch_amount: 1.0
    b: 13.0
    lp: 0.0
    hp: 0.7
    clip_mode: "rgbblend"
  manual:
    d: 1.0
    b: 0.0
    lp: 0.0
    sp: 0.0
    hp: 1.0
    luminance_mode: "HUMAN"
    clip_mode: "rgbblend"
